#!/usr/bin/expect -f
# 使用方法 ./Demo root host originpath
set password zettage321
set username [lindex $argv 0]
set hostip [lindex $argv 1]
set originpath [lindex $argv 2]
set destinationpath [lindex $argv 3]
spawn scp $username@$hostip:$originpath $destinationpath
set timeout 300
expect "$username@$hostip's password:"
set timeout 300
send "$password\r"
set timeout 300
send "exit\r"
expect eof www.2cto.com
