# Kvrocks Replica-3 配置文件
# 端口: 6671 (Master-3 的从节点)

include /etc/kvrocks/base.conf

port 6671
cluster-node-id kvrocks-replica-3

slaveof kvrocks-master-3 6668
slave-read-only yes
slave-ignore-maxmemory yes
